### ISSUE TITLE
Regression with v0.2.0

### ISSUE THREAD

**Issue by zkochan** [pnpm/meta-updater#5]
@ibezkrovnyi if I update `@pnpm/meta-updater` in the pnpm monorepo and I run `pnpm lint:meta`, I get an error:

```
ERROR: undefined is not up-to-dateTypeError: Cannot read property 'split' of undefined
    at Diff.lineDiff.tokenize (/home/zoli/src/pnpm/pnpm-copy/node_modules/.pnpm/diff@4.0.2/node_modules/diff/lib/diff/line.js:43:32)
    at Diff.diff (/home/zoli/src/pnpm/pnpm-copy/node_modules/.pnpm/diff@4.0.2/node_modules/diff/lib/diff/base.js:45:39)
    at diffLines (/home/zoli/src/pnpm/pnpm-copy/node_modules/.pnpm/diff@4.0.2/node_modules/diff/lib/diff/line.js:68:19)
    at structuredPatch (/home/zoli/src/pnpm/pnpm-copy/node_modules/.pnpm/diff@4.0.2/node_modules/diff/lib/patch/create.js:48:3)
    at createTwoFilesPatch (/home/zoli/src/pnpm/pnpm-copy/node_modules/.pnpm/diff@4.0.2/node_modules/diff/lib/patch/create.js:224:14)
    at Object.createPatch (/home/zoli/src/pnpm/pnpm-copy/node_modules/.pnpm/diff@4.0.2/node_modules/diff/lib/patch/create.js:245:10)
    at unified (/home/zoli/src/pnpm/pnpm-copy/node_modules/.pnpm/print-diff@1.0.0/node_modules/print-diff/lib/unified.js:30:22)
    at printDiff (/home/zoli/src/pnpm/pnpm-copy/node_modules/.pnpm/print-diff@1.0.0/node_modules/print-diff/index.js:5:11)
    at printJsonDiff (file:///home/zoli/src/pnpm/pnpm-copy/node_modules/.pnpm/@pnpm+meta-updater@0.2.0/node_modules/@pnpm/meta-updater/lib/index.js:79:5)
    at default (file:///home/zoli/src/pnpm/pnpm-copy/node_modules/.pnpm/@pnpm+meta-updater@0.2.0/node_modules/@pnpm/meta-updater/lib/index.js:26:17)
```

**Comment by ibezkrovnyi** [comment]
Raised PR https://github.com/pnpm/pnpm/pull/5360 with the required changes
